// All-time player registry — no team or season affiliation.
// To add a new player, append to this array.
// Player IDs must be unique and never reused, even if a player leaves and rejoins.
const players = [
    {id: "shan", name: "Istiaque Shanjib"},
    {id: "shaw", name: "Wasif Shawman"},
    {id: "mash", name: "Mashuk Rahman"},
    {id: "aref", name: "Arefin Mohiuddin"},
    {id: "niha", name: "Fardin Islam"},
    {id: "iram", name: "Iram Islam"},
    {id: "nafe", name: "Afsa Nafe"},
    {id: "zahi", name: "Abrar Jalal"},
    {id: "shih", name: "Shihab Chowdhury"},
    {id: "shad", name: "Shadman Chowdhury"},
    {id: "rezw", name: "Rezwan Islam"},
    {id: "shak", name: "Shakib Idris"},
    {id: "owas", name: "Owasif Rahman"},
    {id: "owal", name: "Owalid Rahman"},
    {id: "tays", name: "Tayseer Chowdhury"},
    {id: "saze", name: "Sazed Aftab"},
    {id: "farh", name: "Farhan Ahmed"},
    {id: "eric", name: "Eric Ninthala"},
    {id: "salw", name: "Salwan Sabil"},
    {id: "nibr", name: "Jakwan Hossain"},
    {id: "zami", name: "Zamie Abdullah"},
    {id: "aroy", name: "Arnav Roy"},
    {id: "raki", name: "Rakin Chowdhury"},
    {id: "shaf", name: "Shafeen Hasan"},
    {id: "tanb", name: "Mohammed Uddin"},
    {id: "agho", name: "Arnav Ghosh"},
    {id: "raje", name: "Rajeev Raghavan"},
    {id: "imra", name: "Imran Ghanda"},
    {id: "mehd", name: "Mehdi Islam"},
    {id: "afif", name: "Afif Abdur-Rahman"},
    {id: "priy", name: "Priyak Parvez"},
    {id: "pina", name: "Faisal Abid"},
    {id: "zari", name: "Adnan Jalal"},
    {id: "sami", name: "Samin Basir"},
];
